config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :who_bought, on: :member
  end
  scope '(:locale)' do
    resources :orders
    resources :line_items do
      member do
        post 'decrement_quantity'
      end
    end
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy

  enum pay_type: {
    "Check"          => 0,
    "Credit card"    => 1,
    "Purchase order" => 2
  }

  validates :name, :adress, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys


  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart


  before_action :set_cart, only: [:new, :create]
  before_action :ensure_cart_isnt_empty, only: :new
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @checkout_now = true
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderMailer.received(@order).deliver_later
        format.html { redirect_to store_index_url,
          notice: I18n.t('.thanks') }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :adress, :email, :pay_type)
    end

    def ensure_cart_isnt_empty
      if @cart.line_items.empty?
        redirect_to store_index_url, notice: "Your cart is empty!"
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def payment_type_options
    options_for_select(
    Order::pay_types.
      map {|k,v| I18n.t('orders.payment_types.' + k.parameterize.underscore) } )    
  end
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2
        =raw t('errors.template.header', count: @order.errors.count,
        model: t('activerecord.models.order'))
      %ul
        - @order.errors.full_messages.each do |msg|
          %li
            = raw msg

  .field
    = f.label t('.name')
    = f.text_field :name, size: 40
  .field
    = f.label t('.adress')
    = f.text_area :adress, rows: 3, cols: 40
  .field
    = f.label t('.email')
    = f.email_field :email, size: 40
  .field
    = f.label t('.pay_type')
    = f.select :pay_type, payment_type_options, promt: t('.pay_prompt_html')
  .actions
    = f.submit t('.submit')

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders

%table
  %thead
    %tr
      %th Name
      %th Adress
      %th Email
      %th Pay type
      %th
      %th
      %th

  %tbody
    - @orders.each do |order|
      %tr
        %td= order.name
        %td= order.adress
        %td= order.email
        %td= order.pay_type
        %td= link_to 'Show', order
        %td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
.depot_form
  %fieldset
    %legend
      = t(".legend")
    = render 'form', order: @order

-# = link_to 'Back', orders_path
= link_to 'Back', store_index_path

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @order.name
%p
  %b Adress:
  = @order.adress
%p
  %b Email:
  = @order.email
%p
  %b Pay type:
  = @order.pay_type

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path