config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :who_bought, on: :member
  end
  scope '(:locale)' do
    resources :orders
    resources :line_items do
      member do
        post 'decrement_quantity'
      end
    end
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DepotApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{class: controller.controller_name}
    %div#banner
      = form_tag store_index_path, class: 'locale' do
        = select_tag 'set_locale',
        options_for_select(LANGUAGES, I18n.locale.to_s),
        onchange: 'this.form.submit()'
        = submit_tag 'submit'
        = javascript_tag "$('.locale input').hide()"

      = image_tag 'logo.svg', alt: 'The pragmatic Bookshelf'
      %span.title
        = @page_title
    %div#columns
      %div#side

        - if @cart
          = hidden_div_if(@cart.line_items.empty?, id: 'cart') do
            = render @cart

        %ul
          %li
            = link_to "Home", store_index_path
          %li
            %a{href: ""}
            = t('.questions')
          %li
            %a{href: ""}
            = t('.news')
          %li
            %a{href: ""}
            = t('.contact')
          %li
            = load_time
          %li
          = link_to "LOGIN", login_path

          - if session[:user_id]
            %ul
              %li
                = link_to 'Orders', orders_path
              %li
                = link_to 'Products', products_path
              %li
                = link_to 'Users', users_path
              %li
                = button_to "Logout", logout_path, method: :delete
      %div#main
        = yield